sudo: required
services:
  - docker

before_install:
  - docker build -t felipeballesteros/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true felipeballesteros/docker-react npm run test -- --coverage